name: mehra_app
description: "مشروع فلاتر جديد."
publish_to: 'none' # احذف هذا السطر إذا كنت ترغب في نشره على pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.0+3
  font_awesome_flutter: ^10.8.0
  line_icons: ^2.0.3
  google_sign_in: ^6.3.0
  dropdown_search: ^6.0.2
  google_fonts: ^6.2.1
  curved_navigation_bar: ^1.0.6
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.17
  multi_select_flutter: ^4.1.3
  flutter_form_builder: ^10.0.1 # احتفظ فقط بأحدث إصدار
  eva_icons_flutter: ^3.1.0
  flutter_staggered_grid_view: ^0.7.0
  day_picker: ^2.3.0
  card_swiper: ^3.0.1
  cached_network_image: ^3.4.1
  story_view: ^0.16.5
  image_picker: ^1.1.2
  chewie: ^1.10.0
  video_player: ^2.9.3
  intl: ^0.19.0  # تم تخفيض الإصدار هنا
  firebase_messaging: ^15.2.5
  firebase_database: ^11.3.5
  flutter_local_notifications: ^19.0.0
  firebase_core: ^3.12.1
  flutter_screenutil: ^5.9.3
  photo_manager: ^3.6.4
  provider: ^6.1.2
  uuid: ^4.5.1
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.4
  awesome_dialog: ^3.2.1
  flutter_dropdown_search: ^0.0.4
  cloud_firestore: ^5.6.6
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3


  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Splash.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lang/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf